_extends: .github

repository:
  name: setlistfm
  description: 🔌 Setlist.fm webservice client for php.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, php, library, setlistfm, setlist, api, webservice-client
